### ISSUE TITLE
Update report bugs "By Email" email address

### ISSUE THREAD

**Issue by kesara** [ietf-tools/mailarchive#3835] opened 2024-09-04 00:34 UTC
Change report bugs "By Email" link in the footer to `tools-help [𝖺𝗍] ietf.org`.

**Comment by Androideh700** [comment] 2024-09-07 00:35
- [ ] 

Duplicate of #

**Comment by Androideh700** [comment] 2024-09-07 00:35
Black:abaut

**Comment by Androideh700** [comment] 2024-09-07 00:36
#3667

**Comment by Androideh700** [comment] 2024-09-07 00:37
Write🙋

**Comment by Androideh700** [comment] 2024-09-07 00:38
[``](url)https://github.com/ietf-tools/mailarchive/issues/3835#issue-2504056168

**Comment by Androideh700** [comment] 2024-09-07 00:39
<details><summary>Details</summary>
<p>



</p>
</details>

**Closed** 2024-09-17 23:56 UTC
